### ISSUE TITLE
Create initial project structure

### ISSUE THREAD

**Issue by ilievs** [alehander92/kv#1]

**Comment by alehander92** [comment]
Should we use stack or cabal? A lot of Haskell projects seem to directly
use nix with one of those, but we should focus on something simple

Another option is to just create a standard folder structure without a
package manager or build tool, if we expect to use only the stdlib for now

**Comment by alehander92** [comment]
We decided to use stack, based on https://stackoverflow.com/questions/30913145/what-is-the-difference-between-cabal-and-stack?fbclid=IwAR09E8mXYx7WG-YUvoBu5MbdOMovnRlbM-uK2r_gTvl33YJ3SDnuprQztdY
